// This file is @generated by prost-build.
/// Server注册消息
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerRegister {
    #[prost(uint32, tag = "1")]
    pub server_id: u32,
}
/// Server下线消息
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerDown {
    #[prost(uint32, tag = "1")]
    pub server_id: u32,
}
/// Server信息
#[derive(Eq, Hash)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerInfo {
    #[prost(uint32, tag = "1")]
    pub id: u32,
}
/// 下载请求
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DownloadRequest {
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
}
/// 文件信息响应
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileInfoResponse {
    #[prost(uint64, tag = "1")]
    pub file_size: u64,
    #[prost(uint32, tag = "2")]
    pub chunk_count: u32,
    #[prost(uint64, repeated, tag = "3")]
    pub chunk_sizes: ::prost::alloc::vec::Vec<u64>,
    #[prost(string, tag = "4")]
    pub final_url: ::prost::alloc::string::String,
}
/// 下载元数据
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DownloadMetadata {
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub start_position: u64,
    #[prost(uint64, tag = "3")]
    pub end_position: u64,
}
/// 下载任务
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DownloadTask {
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub start_position: u64,
    #[prost(uint64, tag = "3")]
    pub end_position: u64,
    #[prost(string, tag = "4")]
    pub task_id: ::prost::alloc::string::String,
}
/// 任务结果
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TaskResult {
    #[prost(string, tag = "1")]
    pub task_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub success: bool,
    #[prost(string, tag = "3")]
    pub error_message: ::prost::alloc::string::String,
}
/// 通用消息包装器
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Message {
    #[prost(oneof = "message::Payload", tags = "1, 2, 3, 4, 5, 6, 7, 8")]
    pub payload: ::core::option::Option<message::Payload>,
}
/// Nested message and enum types in `Message`.
pub mod message {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        /// Manager to Server messages
        #[prost(message, tag = "1")]
        ServerRegister(super::ServerRegister),
        #[prost(message, tag = "2")]
        DownloadTask(super::DownloadTask),
        /// Server to Manager messages
        #[prost(message, tag = "3")]
        ServerInfo(super::ServerInfo),
        #[prost(message, tag = "4")]
        ServerDown(super::ServerDown),
        #[prost(message, tag = "5")]
        TaskResult(super::TaskResult),
        /// Client to Manager messages
        #[prost(message, tag = "6")]
        DownloadRequest(super::DownloadRequest),
        /// Manager to Client messages
        #[prost(message, tag = "7")]
        FileInfoResponse(super::FileInfoResponse),
        /// Data transfer
        #[prost(bytes, tag = "8")]
        FileData(::prost::alloc::vec::Vec<u8>),
    }
}
